# Generated by Django 5.2.6 on 2025-09-30 09:21 (Original timestamp kept for continuity)

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Note: All migrations.CreateModel operations for existing tables 
        # (ClientNotes and all managed=False tables) have been removed.
        # This leaves only the operation for the new table: MemberDocument.
        
        migrations.CreateModel(
            name='MemberDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_member_group_code', models.CharField(max_length=255, verbose_name='Member Group Code')),
                ('document_file', models.FileField(upload_to='pdfs/', verbose_name='Document File')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Document Title')),
                ('uploaded_by', models.CharField(max_length=150, verbose_name='Uploaded By')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Member Document',
                'verbose_name_plural': 'Member Documents',
            },
        ),
    ]