# Generated by Django 5.2.6 on 2025-09-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientNotes',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True)),
                ('user', models.TextField(blank=True, db_column='User', null=True)),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
            ],
            options={
                'db_table': 'client_notes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Globalacvv',
            fields=[
                ('mip_names', models.CharField(db_column='MIP Names', max_length=255, primary_key=True, serialize=False)),
                ('branch_code', models.CharField(blank=True, db_column='Branch Code', max_length=255, null=True)),
                ('member', models.CharField(blank=True, db_column='MEMBER', max_length=255, null=True)),
                ('status', models.CharField(blank=True, db_column='STATUS', max_length=255, null=True)),
                ('contribution_amount', models.CharField(blank=True, db_column='CONTRIBUTION AMOUNT', max_length=255, null=True)),
                ('notes', models.CharField(blank=True, db_column='NOTES', max_length=255, null=True)),
                ('schedule_date_received', models.CharField(blank=True, db_column='SCHEDULE DATE RECEIVED', max_length=255, null=True)),
                ('deb_order_date_confirm', models.CharField(blank=True, db_column='DEB ORDER DATE CONFIRM BY EMPOLYER(FUND)', max_length=255, null=True)),
                ('bank_info_upload', models.CharField(blank=True, db_column='Bank info Upload', max_length=225, null=True)),
                ('mg_email_address', models.CharField(blank=True, db_column='MG EMAIL ADDRESS', max_length=225, null=True)),
                ('tel', models.CharField(blank=True, db_column='TEL', max_length=20, null=True)),
            ],
            options={
                'db_table': 'global acvv',
                'managed': False,
            },
        ),
    ]
