"""
Django settings for ACVV_APP project.

Generated by 'django-admin startproject' using Django 5.2.1.
"""
import os
from pathlib import Path
from dotenv import load_dotenv 

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY') 

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*', 'acvv.futura.co.za', 'acvv.futurasa.co.za']

# ==============================================================================
# 📊 DATA UPLOAD SETTINGS (Fixes TooManyFieldsSent error)
# ------------------------------------------------------------------------------
# Default is 1000. Reconciliation worksheets with many rows often exceed this.
# ==============================================================================
DATA_UPLOAD_MAX_NUMBER_FIELDS = 3000

# 1. Trust the secure domain for form submissions
CSRF_TRUSTED_ORIGINS = [
    'https://acvv.futurasa.co.za',
    'https://acvv.futura.co.za',
]

# 2. Handle the Proxy headers from your hoster (Critical for SSL)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# 3. Security tweaks for HTTPS
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Application definition

INSTALLED_APPS = [
    'acvv', 
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware', # Keep disabled if handling legacy PowerApp POSTs
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ACVV_APP.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ACVV_APP.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'), 
        'HOST': os.environ.get('DB_HOST'),
        'PORT': os.environ.get('DB_PORT'),
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = 'dashboard'
LOGIN_URL = 'login'

# ==============================================================================
# 🔑 MICROSOFT GRAPH API SETTINGS (OUTLOOK)
# ==============================================================================
OUTLOOK_EMAIL_ADDRESS = os.environ.get('OUTLOOK_EMAIL_ADDRESS')
CLIENT_ID = os.environ.get('MSGRAPH_CLIENT_ID')
CLIENT_SECRET = os.environ.get('MSGRAPH_CLIENT_SECRET')
TENANT_ID = os.environ.get('MSGRAPH_TENANT_ID')
GRAPH_SCOPES = ['https://graph.microsoft.com/.default']

# Media Settings
MEDIA_URL = '/' 
MEDIA_ROOT = BASE_DIR