"""
Django settings for UNITY_INTERNAL project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
# --- NEW IMPORT: For loading environment variables from .env ---
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- UPDATED: Load environment variables without specifying a path (Step 2 fix) ---
# This makes python-dotenv look for the .env file in the current working directory 
# and up the directory tree, which is often more reliable than a calculated path.
load_dotenv() 


# *******************************************************************
# ADDED: Explicitly set OAUTHLIB_INSECURE_TRANSPORT for local HTTP testing
# This is required because the client is configured as a Web App but runs on HTTP.
# This must be set before Google libraries are initialized.
if os.getenv('DJANGO_ENV', 'development') == 'development':
    os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'
# *******************************************************************


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# --- UPDATED: Load SECRET_KEY from environment variables ---
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*','internalunity.futura.co.za']


# Application definition

INSTALLED_APPS = [
    'unity_internal_app',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'UNITY_INTERNAL.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'UNITY_INTERNAL.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        # --- UPDATED: Load database settings from environment variables ---
        'NAME': os.getenv('DB_NAME'), 
        'USER': os.getenv('DB_USER'), 
        'PASSWORD': os.getenv('DB_PASSWORD'), 
        'HOST': os.getenv('DB_HOST', 'localhost'),  # Use fallback for HOST
        'PORT': os.getenv('DB_PORT', '3306'),      # Use fallback for PORT
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login/' # or '/login/'

# ==============================================================================
# 🔑 MICROSOFT GRAPH API SETTINGS (OUTLOOK)
# ------------------------------------------------------------------------------
# 🛑 ALL VALUES LOADED FROM .ENV 🛑
# ==============================================================================

# 1. The external mailbox/user account you are connecting to (UserPrincipalName)
OUTLOOK_EMAIL_ADDRESS = os.environ.get('OUTLOOK_EMAIL_ADDRESS')

# 2. Your Application's credentials (Client ID)
CLIENT_ID = os.environ.get('MSGRAPH_CLIENT_ID')

# 3. Your Application's Client Secret (Secret Key)
CLIENT_SECRET = os.environ.get('MSGRAPH_CLIENT_SECRET')

# 4. The Tenant ID (Directory ID) for the Azure AD/Entra ID instance
TENANT_ID = os.environ.get('MSGRAPH_TENANT_ID')

# 5. The scopes required for the Graph API calls.
# MUST use the .default scope for the Client Credentials Flow.
GRAPH_SCOPES = [
    'https://graph.microsoft.com/.default'
]

# ==============================================================================
# END MICROSOFT GRAPH API SETTINGS
# ==============================================================================